Feature/#24 ExitAction 구현
CamIsTrick/CIT_backend pull request #39
Opened 2024-03-15 07:51 UTC by TrixieL20

#24 코드 리뷰 부탁드립니다.

2024-03-15 11:17 UTC, yujeongkwon requested changes
전체적으로 깔끔한 코드인 것 같습니다!

2024-03-15 11:17 UTC, yujeongkwon commented on src/main/java/cit/camistrick/action/ExitAction.java
> +                .orElseThrow(NoSuchElementException::new);
이 친구도 getUsreSessoin() 메소드 처럼 getLevaingRoom() 메소드로 분리하면 더 가독성이 좋아지지 않을까요?!

2024-03-15 11:17 UTC, yujeongkwon commented on src/main/java/cit/camistrick/action/ExitAction.java
> +        roomManager.removeRoom(leavingRoom);
해당 클래스에서 의미하는 Exit은 한 사용자가 방을 나가는 경우아닌가요? 
 위처럼 작성하면 한 사용자가 방에서 나가는 경우, 방 전체의 사용자들이 나가지는 문제가 생길 것 같습니다! 
 제 생각으로는 사용자가 떠나고 난 후, 만약 방안에 사용자가 아무도 없다면 rommManager.removeRoom() 메소드를 호출하면 좋을 것 같아요!

2024-03-16 05:02 UTC, howudong commented on src/main/java/cit/camistrick/action/ExitAction.java
> +        roomManager.removeRoom(leavingRoom);
동의합니다! 방에 사람이 있는데, 방을 없애버리면 안될거같아요!

2024-03-16 08:26 UTC, TrixieL20 commented on src/main/java/cit/camistrick/action/ExitAction.java
> +        roomManager.removeRoom(leavingRoom);
다시 확인해보고 수정하겠습니다!

2024-03-16 11:49 UTC, TrixieL20 commented on src/main/java/cit/camistrick/action/ExitAction.java
> +                .orElseThrow(NoSuchElementException::new);
그럴 것 같네요
그리고 더 통일성이 있을 것 같네요

2024-03-16 12:15 UTC, howudong approved these changes

2024-03-16 12:15 UTC, howudong commented on src/main/java/cit/camistrick/action/ExitAction.java
> +    }
좋습니다~!!

2024-03-17 07:40 UTC, yujeongkwon approved these changes

2024-03-19 10:05 UTC, merged